@startuml
actor Users as user
box "VCO UI"
participant "SDWAN UI" as sdwan_ui
end box
box "VCO"
participant "portal" as portal
participant "Arista FW consumer" as consumer
participant "redis streams" as redis
participant "mysql" as mysql
end box
box "Arista FW"
participant "Arista FW Backend" as arista_fw_backend
end box
user --> portal : create edge
activate portal #LightBlue
portal -> portal : process the request
portal -> redis: Add message to topic AristaFW \n with details of edge and arista profile
portal -> user : Response
deactivate portal
activate consumer #LightBlue
consumer <- redis : Consume & validate new message
consumer -> arista_fw_backend: Send request to create edge
arista_fw_backend -> arista_fw_backend: Create appliances
arista_fw_backend -> consumer: Response with applianceId
consumer -> mysql: store applianceId in EDGE_PROPERTIES table
deactivate consumer

@enduml 

